PRAGMA foreign_keys = ON;

CREATE TABLE PATIENT (
    PATIENT_ID     INTEGER PRIMARY KEY,
    MRN            TEXT    NOT NULL UNIQUE,
    FIRST_NAME     TEXT    NOT NULL,
    LAST_NAME      TEXT    NOT NULL,
    DATE_OF_BIRTH  TEXT    NOT NULL,
    SEX            TEXT    CHECK (SEX IN ('M','F','O')),
    PHONE          TEXT,
    EMAIL          TEXT,
    ADDRESS_LINE   TEXT,
    CITY           TEXT,
    STATE          TEXT,
    ZIP            TEXT
);

CREATE TABLE PORTAL_ACCOUNT (
    ACCOUNT_ID     INTEGER PRIMARY KEY,
    FK_PATIENT_ID  INTEGER NOT NULL UNIQUE,
    USERNAME       TEXT    NOT NULL UNIQUE,
    PASSWORD_HASH  TEXT    NOT NULL,
    LAST_LOGIN     TEXT,
    IS_ACTIVE      INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    FOREIGN KEY (FK_PATIENT_ID) REFERENCES PATIENT (PATIENT_ID)
);

CREATE TABLE PROVIDER (
    PROVIDER_ID    INTEGER PRIMARY KEY,
    NPI            TEXT    NOT NULL UNIQUE,
    FIRST_NAME     TEXT    NOT NULL,
    LAST_NAME      TEXT    NOT NULL,
    SPECIALTY      TEXT    NOT NULL,
    PHONE          TEXT,
    EMAIL          TEXT
);

CREATE TABLE LOCATION (
    LOCATION_ID    INTEGER PRIMARY KEY,
    LOCATION_NAME  TEXT    NOT NULL,
    ADDRESS_LINE   TEXT,
    CITY           TEXT,
    STATE          TEXT,
    ZIP            TEXT,
    PHONE          TEXT
);

CREATE TABLE APPOINTMENT (
    APPOINTMENT_ID   INTEGER PRIMARY KEY,
    FK_PATIENT_ID    INTEGER NOT NULL,
    FK_PROVIDER_ID   INTEGER NOT NULL,
    FK_LOCATION_ID   INTEGER NOT NULL,
    SCHEDULED_START  TEXT    NOT NULL,
    SCHEDULED_END    TEXT    NOT NULL,
    STATUS           TEXT    NOT NULL DEFAULT 'Scheduled'
                     CHECK (STATUS IN ('Scheduled','Checked In','Completed','Cancelled','No-Show')),
    REASON           TEXT,
    FOREIGN KEY (FK_PATIENT_ID)  REFERENCES PATIENT  (PATIENT_ID),
    FOREIGN KEY (FK_PROVIDER_ID) REFERENCES PROVIDER (PROVIDER_ID),
    FOREIGN KEY (FK_LOCATION_ID) REFERENCES LOCATION (LOCATION_ID)
);

CREATE TABLE ENCOUNTER (
    ENCOUNTER_ID      INTEGER PRIMARY KEY,
    FK_APPOINTMENT_ID INTEGER NOT NULL UNIQUE,
    ENCOUNTER_DATE    TEXT    NOT NULL,
    CHIEF_COMPLAINT   TEXT,
    VISIT_NOTE        TEXT,
    STATUS            TEXT    NOT NULL DEFAULT 'Open'
                      CHECK (STATUS IN ('Open','Signed')),
    SIGNED_AT         TEXT,
    FOREIGN KEY (FK_APPOINTMENT_ID) REFERENCES APPOINTMENT (APPOINTMENT_ID)
);

CREATE TABLE DIAGNOSIS (
    DIAGNOSIS_ID   INTEGER PRIMARY KEY,
    ICD10_CODE     TEXT    NOT NULL UNIQUE,
    DESCRIPTION    TEXT    NOT NULL,
    CATEGORY       TEXT
);

CREATE TABLE ENCOUNTER_DIAGNOSIS (
    ENCOUNTER_DIAGNOSIS_ID INTEGER PRIMARY KEY,
    FK_ENCOUNTER_ID        INTEGER NOT NULL,
    FK_DIAGNOSIS_ID        INTEGER NOT NULL,
    IS_PRIMARY             INTEGER NOT NULL DEFAULT 0 CHECK (IS_PRIMARY IN (0,1)),
    NOTED_DATE             TEXT,
    UNIQUE (FK_ENCOUNTER_ID, FK_DIAGNOSIS_ID),
    FOREIGN KEY (FK_ENCOUNTER_ID) REFERENCES ENCOUNTER (ENCOUNTER_ID),
    FOREIGN KEY (FK_DIAGNOSIS_ID) REFERENCES DIAGNOSIS (DIAGNOSIS_ID)
);

CREATE TABLE INVOICE (
    INVOICE_ID      INTEGER PRIMARY KEY,
    FK_ENCOUNTER_ID INTEGER NOT NULL UNIQUE,
    INVOICE_DATE    TEXT    NOT NULL,
    TOTAL_AMOUNT    REAL    NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    AMOUNT_PAID     REAL    NOT NULL DEFAULT 0 CHECK (AMOUNT_PAID >= 0),
    STATUS          TEXT    NOT NULL DEFAULT 'Open'
                    CHECK (STATUS IN ('Open','Partial','Paid')),
    FOREIGN KEY (FK_ENCOUNTER_ID) REFERENCES ENCOUNTER (ENCOUNTER_ID)
);

CREATE TABLE PAYMENT (
    PAYMENT_ID     INTEGER PRIMARY KEY,
    FK_INVOICE_ID  INTEGER NOT NULL,
    PAYMENT_DATE   TEXT    NOT NULL,
    AMOUNT         REAL    NOT NULL CHECK (AMOUNT > 0),
    METHOD         TEXT    NOT NULL
                   CHECK (METHOD IN ('Card','Cash','Check','Insurance')),
    FOREIGN KEY (FK_INVOICE_ID) REFERENCES INVOICE (INVOICE_ID)
);
